### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by HilbertMaximov** [cwmok/DIRAC#1]
Dear author, hello, I would like to ask when will your code be published on github?And I would like to ask if your code is suitable for 2d data?or is there a version of the code for 2d datasets?Sincerely look forward to your reply.😀

**Comment by cwmok** [comment]
Hi @HilbertMaximov,

Thanks for your interest in our work. 
Since we applied our method to this year's Brats-Reg challenge https://www.med.upenn.edu/cbica/brats-reg-challenge/ in MICCAI, we plan to release the code after the oral presentation at the Brats-Reg workshop (by the end of September) to avoid any conflict in interest. 

I was told by the challenge organizer that our method is ranked within the top 3 performing ones and I was invited to give an oral presentation of our method at the Brats-Reg workshop. If you are also interested in how to apply this method to the challenge and achieve good results in pre-operative and follow-up MR registration. Feel free to register for the workshop in MICCAI.

The idea of the work is applicable to 2d data. But I will release the code for the Brats-Reg data (3D data) first. If you have any interesting 2d datasets that have the missing correspondence issue, free feel to let me know and I may build a 2d version for it.

Sorry for the delay. I have a hectic schedule recently.

Regards,
Tony

**Comment by HilbertMaximov** [comment]
> Hi @HilbertMaximov,
> 
> Thanks for your interest in our work. Since we applied our method to this year's Brats-Reg challenge https://www.med.upenn.edu/cbica/brats-reg-challenge/ in MICCAI, we plan to release the code after the oral presentation at the Brats-Reg workshop (by the end of September) to avoid any conflict in interest.
> 
> I was told by the challenge organizer that our method is ranked within the top 3 performing ones and I was invited to give an oral presentation of our method at the Brats-Reg workshop. If you are also interested in how to apply this method to the challenge and achieve good results in pre-operative and follow-up MR registration. Feel free to register for the workshop in MICCAI.
> 
> The idea of the work is applicable to 2d data. But I will release the code for the Brats-Reg data (3D data) first. If you have any interesting 2d datasets that have the missing correspondence issue, free feel to let me know and I may build a 2d version for it.
> 
> Sorry for the delay. I have a hectic schedule recently.
> 
> Regards, Tony

Hi!

Since you previously release the code, I was trying to apply to the hospital for  2d datasets, last time you mentioned that your work can also be used for 2d datasets, but I found that I had some difficulty making changes on your 3d code, would you please build a 2d version of DIRAC?
And may I get your Wechat number if you have?My email address is 2467826379@qq.com

Thanks.
